# Generated by Django 3.0.8 on 2020-08-20 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200818_1701'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='meeting',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
