# Generated by Django 3.0.8 on 2020-08-20 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200820_0858'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='is_teacher',
        ),
    ]
