# Generated by Django 3.0.8 on 2020-08-20 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_myuser_groupid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='groupId',
        ),
    ]
