# Generated by Django 3.0.8 on 2020-08-20 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_myuser_groupid'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='groupId',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, to='api.MyGroup'),
        ),
    ]
