# Generated by Django 3.0.8 on 2020-08-20 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_myuser_groupid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='groupId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.MyGroup'),
        ),
    ]
