# Generated by Django 3.0.8 on 2020-08-26 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20200820_1057'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserGroupMapping',
        ),
    ]
