# Generated by Django 3.0.8 on 2020-09-16 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20200916_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='availability',
            field=models.CharField(default='1900-2100', max_length=256),
        ),
    ]
