# Generated by Django 3.0.8 on 2020-09-16 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_myuser_availability'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_statement', models.CharField(max_length=265)),
                ('problem_link', models.CharField(max_length=256)),
            ],
        ),
        migrations.RenameField(
            model_name='mygroup',
            old_name='groupName',
            new_name='name',
        ),
    ]
