# Generated by Django 3.0.8 on 2020-10-05 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20201005_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='name',
            field=models.CharField(default='New Student', max_length=256),
        ),
    ]
