# Generated by Django 3.0.8 on 2020-10-05 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20201005_2301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='rating',
        ),
    ]
