# Generated by Django 3.0.8 on 2020-10-06 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_remove_myuser_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='rating',
        ),
    ]
