# Generated by Django 3.0.8 on 2020-10-12 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20201006_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='name',
            field=models.CharField(default='New Student', max_length=256, null=True),
        ),
    ]
