# Generated by Django 3.0.8 on 2020-10-12 11:01

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_auto_20201012_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='groupId',
            field=models.ForeignKey(default=api.models.get_default_group, on_delete=django.db.models.deletion.CASCADE, to='api.MyGroup'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='is_student',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
