# Generated by Django 3.0.8 on 2020-10-14 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_auto_20201012_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mygroup',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
