# Generated by Django 3.0.8 on 2020-10-16 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_auto_20201014_0602'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='receiverId',
            new_name='receiver_id',
        ),
        migrations.RenameField(
            model_name='meeting',
            old_name='groupId',
            new_name='group_id',
        ),
        migrations.RenameField(
            model_name='myuser',
            old_name='groupId',
            new_name='group_id',
        ),
    ]
