# Generated by Django 3.0.8 on 2020-10-18 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_auto_20201016_1239'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meeting',
            old_name='user',
            new_name='users',
        ),
    ]
