# Generated by Django 3.1.2 on 2020-11-23 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_auto_20201119_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='group_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.mygroup'),
        ),
    ]
